### PR TITLE
Import different addressbooks (stable7 branch backport)

### PR DESCRIPTION
**Pull request by babelouest**
Backport of #735 into stable7 branch
to be able to import in different addressbooks without having to reload the page

### CODE REVIEW

**Comment by thailgrott** [comment]
I'd like to say that I tried this, but the stable7 branch didn't seem to work for me today.

**Comment by babelouest** [comment]
@ostami , that's weird, I just retested it and it works fine for me, how did you test this PR ?

**Comment by thailgrott** [comment]
This is from memory. I did the test on a fresh Debian 7 Wheezy virtual machine. I then installed php5, libapache2-mod-php5, php5-gd, mysql-server, mysql-client. Next, did a "a2enmod rewrite". Then in /var/www I did a, "git clone https://github.com/owncloud/core.git" and changed all files and folders to www-data:www-data for the /var/www/core folder and contents recursively. I entered the core folder and did a, "git checkout stable7" and tried to load the page. The page was blank. I had an apache error log about missing php files. I tried, "git submodule update --init" from an owncloud githup report with the same missing file. Still having the blank page I did a "git status" and there were missing files.

<pre>
root@owncloud1:/var/www/core# git status 
# On branch stable7
# Changes not staged for commit:
#   (use "git add/rm <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       deleted:    COPYING-AGPL
#       deleted:    core/css/jquery-tipsy.css
#       deleted:    core/js/jquery-tipsy.js
#       deleted:    core/l10n/xgettextfiles
#
no changes added to commit (use "git add" and/or "git commit -a")
</pre>

 So I tried, "git reset HEAD ." in the /var/www/core folder. 

Edit:
Actually reviewing this, I see that those files are still missing (DELETED). This is just me learning git better. I now did the following to fix.

<pre>
root@owncloud1:/var/www/core# git reset --hard HEAD
HEAD is now at fb63e75 Merge pull request #12643 from owncloud/ldap-user-cleanup-stable7
root@owncloud1:/var/www/core# git status
# On branch stable7
nothing to commit (working directory clean)
root@owncloud1:/var/www/core# 
</pre>

Now I get the install page. I'm not sure where I made my trouble. Maybe deleting all the files when I was in the stable branch and then switching to stable7. I'll see if I can pull your patch and give it a try.

**Comment by babelouest** [comment]
Since this PR is derived from stable, you have to checkout the branch stable7 from core first, then the command `git submodule --init`, then checkout this PR in contacts.

I retried earlier like this and it worked on my side.

**Comment by thailgrott** [comment]
Well I'm in the stable7 branch and that definitely works with what I outlined above and forgot. I mean it allows me to finish the install. I then changed to apps directory and did a "git clone https://github.com/owncloud/contacts.git". I got the message, this is not a compatible app. for your version of owncloud, until I changed the user and group to www-data. But I'm now getting a blank page just when I go to the contact app. The data/owncloud.log give:

<pre>
{"app":"PHP","message":"Call to undefined function vendor_script() at \/var\/www\/gh-owncloud7\/apps\/contacts\/templates\/contacts.php#28","level":3,"time":"2014-12-24T04:41:37+00:00"}
</pre>

I was looking at http://blog.jacius.info/git-submodule-cheat-sheet/ and tried the following, not completely from the link, but I'm not seeing how it's updating anything to provide any missing files.

<pre>
git submodule add https://github.com/owncloud/contacts.git subm/contacts/
git submodule update --init
git pull origin
git submodule update
</pre>

With the above I didn't see any new errors in data/owncloud.log but still a blank page on just the contacts app - even check clearing cache. 

I think you all have bigger problems to work on. I'll probably search this one out later. But I just wanted to let you know I tried to check out the changes.

**Comment by thailgrott** [comment]
Well for kicks, I tried to pull in the this fix. I thought I'd want to test the before and after in stable7, but pulling this in definitely does something.

<pre>
root@owncloud1:/var/www/gh-owncloud7/subm/contacts# git fetch origin pull/736/head:736
From https://github.com/owncloud/contacts
 * [new ref]         refs/pull/736/head -> 736
root@owncloud1:/var/www/gh-owncloud7/subm/contacts# git branch
  736
* master
root@owncloud1:/var/www/gh-owncloud7/subm/contacts# git checkout 736
Switched to branch '736'
</pre>

After the above, the page is not totally blank, but I can see why the page doesn't have much functionality. As when I check the chrome console there are a few 404s. But rechecking the 404s seem random - not always the same files.

<pre>
owncloud1/:32 GET http://owncloud1/gh-owncloud7/apps2/contacts/css/jquery.combobox.css?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:33 GET http://owncloud1/gh-owncloud7/apps2/contacts/css/jquery.ocaddnew.css?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:35 GET http://owncloud1/gh-owncloud7/apps2/contacts/css/contacts.css?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:64 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/loader.js?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:65 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/admin.js?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:72 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/jquery.combobox.js?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:73 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/modernizr.custom.js?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:74 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/app.js?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:75 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/addressbooks.js?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:76 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/contacts.js?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:77 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/storage.js?v=97fbff308508c1b4cdb3497bb879ada0 404 (Not Found)
owncloud1/:78 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/groups.js?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:79 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/jquery.ocaddnew.js?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:80 GET http://owncloud1/gh-owncloud7/apps2/contacts/js/otherbackendconfig.js?v=97fbff308508c1b4cdb3497bb879ada0 
owncloud1/:162 GET http://owncloud1/gh-owncloud7/apps2/contacts/img/contacts.svg 404 (Not Found)
owncloud1/:162 GET http://owncloud1/gh-owncloud7/apps2/contacts/img/contacts.svg 404 (Not Found)
</pre>

In the firefox console I noted the following errors.

<pre>
[01:32:54.965] SyntaxError: Using //@ to indicate source map URL pragmas is deprecated. Use //# instead @ http://owncloud1/gh-owncloud7/core/js/jquery-1.10.0.min.js?v=97fbff308508c1b4cdb3497bb879ada0:1
[01:29:06.421] Content Security Policy: Directive inline script base restriction violated @ http://owncloud1/gh-owncloud7/index.php?redirect_url=%2Fgh-owncloud7%2Findex.php%2Fapps%2Fcontacts%2F
[01:32:56.071] Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. @ http://owncloud1/gh-owncloud7/core/js/jquery-1.10.0.min.js?v=97fbff308508c1b4cdb3497bb879ada0:5
</pre>

Git status shows working directory clean, and there are no errors in data/owncloud.log.

<pre>
root@owncloud1:/var/www/gh-owncloud7/subm/contacts# git status
# On branch 736
nothing to commit (working directory clean)
</pre>

As a personal note, the following just put the contact in some, "no branch", and I had to switch back.

<pre>
root@owncloud1:/var/www/gh-owncloud7# git submodule update --init
Submodule '3rdparty' () registered for path '3rdparty'
Submodule 'subm/contacts' () registered for path 'subm/contacts'
Submodule path 'subm/contacts': checked out '308241a0f595da4f47081910968b1a1276be9387'
</pre>

<pre>
root@owncloud1:/var/www/gh-owncloud7/subm/contacts# git branch
* (no branch)
  736
  master
root@owncloud1:/var/www/gh-owncloud7/subm/contacts# git checkout 736
Previous HEAD position was 308241a... Merge pull request #706 from owncloud/fix_704
Switched to branch '736'
</pre>

**Comment by DeepDiver1975** [comment]
Let's focus on contacts for oc8.1 -> close - THX

**Comment by babelouest** [comment]
:+1:

**Pull request closed without merging**
