### PR TITLE
fix import fileupload filter which had only text/vcard and text/x-vcard (stable7 backport)

### PR DESCRIPTION
**Pull request by babelouest**

### CODE REVIEW

**Comment by jbtbnl** [comment]
@Pastafarianist please check if this fix solves #771 for you!

**Comment by Pastafarianist** [comment]
@jbtbnl I'm on stable branch and I'm afraid I can't do that.

**Comment by dniku** [comment]
@jbtbnl Yes, it is fixed. Thanks!

**Comment by jancborchardt** [comment]
@babelouest @DeepDiver1975 is this still current? Do we do stable7 backports?

**Comment by DeepDiver1975** [comment]
I vote for looking at the future of this app in the context of oc8 and oc8.1

**Pull request closed without merging**
