### PR TITLE
Extracting closures into methods to solve php 5.3 issue #546

### PR DESCRIPTION
**Pull request by th3fallen**

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Sounds good. Is there any Info, when a new version with this patch will arrive?

2014-07-24_10h22_21

**Comment by icewind1991** [comment]
Code looks good :+1:

**Comment by babelouest** [comment]
code looks good to me too

**Comment by DeepDiver1975** [comment]
bringing it all together in https://github.com/owncloud/contacts/pull/568 - THX

**Pull request closed without merging**
