### PR TITLE
add confirmation before deleting an addressbook

### PR DESCRIPTION
**Pull request by babelouest**
new proposition for a addressbook deletion confirmation.
Got the inspiration from @rehrumesh 's work: https://github.com/owncloud/contacts/pull/787
but replaced the classic confirmation dialog by the owncloud one.

### CODE REVIEW

**Comment by jancborchardt** [comment]
So @rehrumesh @ccoenen can you review this? And does this replace https://github.com/owncloud/contacts/pull/787 ?

**Comment by rehrumesh** [comment]
Yes this will replace #787 . @babelouest has provided improved code. I think this PR can be merged.

**Comment by jancborchardt** [comment]
@babelouest @rehrumesh can you look at the Travis CI failures then? And we need another review here, @ccoenen @jbtbnl @LEDfan maybe? :)

**Comment by PhilipLeiva** [comment]
I checked this out on v8.1.0beta2 of core, and I get the following error.

```
{"reqId":"U8zXy2Oat4q+J8xfpKTr","remoteAddr":"127.0.0.1","app":"PHP","message":"Access to undeclared static property: Sabre\\VObject\\Component::$classMap at \/owncloud\/apps\/contacts\/appinfo\/app.php#15","level":3,"time":"2015-06-12T08:25:51+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps"}
```

**Comment by PhilipLeiva** [comment]
I copied the code to a stable branch, and the front end of the script works well. The back end produces a message, which may be related and worth looking into before merging.

```
{"reqId":"gsNaowQddbB9dp8gQoMB","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-12T08:47:17+00:00","method":"DELETE","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/5"}
```

**Comment by DeepDiver1975** [comment]
works :+1:

**Comment by jancborchardt** [comment]
@aidanamavi you still getting the errors? @babelouest anything to add?

**Pull request merged**
