### PR TITLE
Solve the 404 contact not found error #623

### PR DESCRIPTION
**Pull request by LEDfan**
See why this solve the bug here: https://github.com/owncloud/contacts/issues/623#issuecomment-54740843

### CODE REVIEW

**Comment by LEDfan** [comment]
@jancborchardt @DeepDiver1975 @jbtbnl @babelouest can you please test if this introduces new problems and solve the error in #623? Thanks!

**Comment by LEDfan** [comment]
When can this be merged? This should also be backported since this creates bugs with all apps using the `ContactsManager`. @karlitschek

**Comment by LEDfan** [comment]
@karlitschek can I backport to stable7? Tnx.

**Comment by karlitschek** [comment]
Of course :-)

**Comment by LEDfan** [comment]
Great!
5e714a7e8ef1635a63db25bc44023b9de0ca33f6
2bf76c213c1202e105d4cad42cf97d4916f03de1
3d4224a090d07425fa2c0e4ed114a3326ccdab4a

(Realized after pushing that a squash would be better...)

**Comment by enoch85** [comment]
Is this provided with 7.0.3?

**Comment by jbtbnl** [comment]
@enoch85 Yes, the commits are in stable7 so it should end up in 7.0.3.

**Pull request merged**
