### PR TITLE
cleanup travis.yml and scrutnizer.yml

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
I have no clue about the failing unit tests ....

**Comment by DeepDiver1975** [comment]
please review @LukasReschke @ockham @nickvergessen @MorrisJobke @jakobsack @PVince81

**Comment by LukasReschke** [comment]
:rocket:

**Comment by MorrisJobke** [comment]
:tada:

**Pull request merged**
