### PR TITLE
pass addressBookId as addressBookId, not parent

### PR DESCRIPTION
**Pull request by gvde**
backport of #1134 to stable8.2

### CODE REVIEW

**Comment by Georg-Git** [comment]
Checked, no index errors in OC Log.

:+1:

@fossxplorer please help merging.

I think we have to ride this old horse still for a while even with OC 9.0 knocking at the door....

**Comment by jancborchardt** [comment]
@gvde @Georg-Git @babelouest you are aware of the CardDAV backend moving into core for 9.0 as well as a new Contacts frontend being in the works, right? See https://github.com/owncloud/contactsrework – would be great to join forces here :)

FYI @Henni @DeepDiver1975

**Comment by gvde** [comment]
@jancborchardt I know that. That's why I don't spend any time trying to fix anything bigger. I have fixed to get it working for what I need at the moment. There are a couple of frontend issues but I can live with that for the time being. Other then that, I fix smaller things like this one.

I guess when the new frontend is in beta I might consider switching and help debugging. As I don't really have the time to do a lot of testing of alpha software in a test environment...

**Comment by Georg-Git** [comment]
@jancborchardt same with me.

I want to preserve my existing contacts in current OC Version - hopefully loosing not to much of them until OC 9.0 comes true. The last year it was really dark in this valley.
;-)

**Comment by jancborchardt** [comment]
@gvde @Georg-Git yeah, sorry about the issues. We hope that with the main sync in core and the separation of the frontend it will be much better. Good to hear you will be on board for the new apps then as well – especially for the new Contacts we still need more testers and contributors. :)

**Comment by gvde** [comment]
The separation of carddav from the frontend is definitely much better. No need for "hope" here. IMHO it'll be a much clearer design and superior to the current state...

**Comment by Georg-Git** [comment]
So - enough small talk - back to business.
The winter is cold and will still last for some months, especially for this app.
;-)

@jancborchardt
Please spent some bread of charity and merge this and the related PRs of gvde:
https://github.com/owncloud/contacts/pull/1136 OC 8.2, this one
https://github.com/owncloud/contacts/pull/1135 OC 8.1
https://github.com/owncloud/contacts/pull/1134 OC master, hopefully not needed due to OC 9.0

**Comment by jancborchardt** [comment]
@Georg-Git I can’t do any code review there unfortunately (am designer). Calling @DeepDiver1975 @Henni for help on reviewing / merging those. @Georg-Git I assume you already tested and reviewed the pull requests as well?

**Comment by Georg-Git** [comment]
Tested and reviewed, as already documented in my comment at the top of this PR.

**Pull request merged**
