### PR TITLE
restrict addressbookprovider-search to its addressbook in oc7

### PR DESCRIPTION
**Pull request by lupusmeatus**
backport of #857

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by ghost** [comment]
FYI, seems that broke PHP 5.3 support in oC7: https://github.com/owncloud/contacts/issues/981

**Comment by DeepDiver1975** [comment]
> FYI, seems that broke PHP 5.3 support in oC7: #981

indeed - instead of

``` php
$params[] = $this->addressBook->getMetaData()['id'];
```

we need

``` php
$meta = $this->addressBook->getMetaData();
$params[] = $meta['id'];
```

**Comment by ghost** [comment]
Fix is in https://github.com/owncloud/contacts/issues/995

**Pull request merged**
