### PR TITLE
Fix "Undefined index: REQUEST_URI" on cron runs

### LINKED ISSUE #972: Undefined index: REQUEST_URI after update contacts 0.4.0.0 on oC 8.1
Not using the issue template as this is very likely just the same as in the calendar app https://github.com/owncloud/calendar/issues/714 which got fixed by https://github.com/owncloud/calendar/commit/3e4a1e1a241479c2c3c5be60379c520c421ce8c0

This is happening on contacts 0.4.0.0 with oC 8.1 when cron runs (from cli) where REQUEST_URI is not set.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #972 

Similar/same fix as in calendar with https://github.com/owncloud/calendar/commit/3e4a1e1a241479c2c3c5be60379c520c421ce8c0

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by jospoortvliet** [comment]
Looks like Documents also needs this fix... https://github.com/owncloud/documents/issues/502#issuecomment-120057626

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @RealRancor Backport this to fix 8.1 instances?

**Comment by ghost** [comment]
@MorrisJobke Seems it was already backported to 8.1: https://github.com/owncloud/contacts/commit/b45fd6a93ec4c090f1cef1e87af8fae3a545af82

Maybe worth a new release of the contacts app together with the fix for birthdays.

**Comment by DeepDiver1975** [comment]
> Maybe worth a new release of the contacts app together with the fix for birthdays.

We should do this.

**Pull request merged**
