### PR TITLE
pass addressBookId as addressBookId, not parent

### PR DESCRIPTION
**Pull request by gvde**
fixes error message "Undefined index: addressBookId at /var/www/owncloud/apps/contacts/lib/hooks.php#109"
fix for #1127

### CODE REVIEW

**Comment by Georg-Git** [comment]
@gvde = last man standing, still riding this old horse until end of its life ;-)))

Thank You very much for Your perseverance and endurance!!!

**Comment by Georg-Git** [comment]
This PR did not fix the problem:
still the same undefined Index Error in OC Log when creating a new contact.

**Comment by gvde** [comment]
Hmm. Odd things happening. For whatever reason, the string was all lower case... Now check again. Note the upper case letters in 'addressBookId'...

**Comment by Georg-Git** [comment]
Adding, Editing, Deleting Contacts in OC Apps:
No index errors in OC Log anymore!
=> Fixed

**Comment by Georg-Git** [comment]
Checked, no index errors in OC Log.

:+1:

@fossxplorer please help merging.

I think we have to ride this old horse still for a while even with OC 9.0 knocking at the door....

**Pull request merged**
