### PR TITLE
Fix untranslated texts

### PR DESCRIPTION
**Pull request by vgezer**
Three strings in contacts template were missing. This should help use
of existing strings to be used in contacts app.

### CODE REVIEW

**Comment by jbtbnl** [comment]
This is already part of #290.

**Comment by vgezer** [comment]
@jbtbnl  In which branch is this fix?

**Comment by jbtbnl** [comment]
@wakeup it is in https://github.com/jbtbnl/contacts

**Comment by vgezer** [comment]
Aha yes, i hope it will be merged soon then.

**Comment by jancborchardt** [comment]
Aaaand it’s merged! Thank you @wakeup for the pull request even though it was fixed through another pull request. :) Keep it up with the awesome contributions!

**Pull request closed without merging**
