### PR TITLE
fix caldav when the calendar app is only enabled for specific groups

### PR DESCRIPTION
**Pull request by icewind1991**
Since checking if an app is enabled requires a user to be logged in we need to postpone those checks until after the *DAV auth is handled.

Requires owncloud/core#9962

### CODE REVIEW

**Comment by jancborchardt** [comment]
@schiesbn @DeepDiver1975 can you test this, together with https://github.com/owncloud/core/pull/9962

**Comment by jancborchardt** [comment]
@ben-denham @ockham @babelouest can you please review this one?

**Comment by ockham** [comment]
Sorry, I know too little about this to be qualified to review.

**Comment by babelouest** [comment]
@icewind1991 , I understand the first change, but what does the second has to do with this bug ? Is it another way of detecting if the app contact is enabled ?

**Comment by icewind1991** [comment]
Yes, it checks if the app is enabled _after_ webdav auth is done

**Comment by PVince81** [comment]
Works in combination with #9962 :+1:

**Comment by LukasReschke** [comment]
Works :+1:

**Pull request merged**
