### PR TITLE
Change "vcardcountry" to "c" for HOME ADR

### PR DESCRIPTION
**Pull request by makuser**
Instead of "vcardcountry", "c" is used for "RFC2256: ISO-3166 country 2-letter code" in objectClass "inetOrgPerson".

### CODE REVIEW

**Comment by jbtbnl** [comment]
CC @babelouest

**Comment by babelouest** [comment]
I had to go through my openldap schema to figure out why I put this, it's because the 'c' attribute is not present in the inetOrgPerson.schema file, but it exists in the core.schema...
I'll run some tests to validate this, thanks.

**Comment by jbtbnl** [comment]
@babelouest any news on this?

**Comment by babelouest** [comment]
I've tested it in the last days and the change itself seems fine.
I saw potential other problems with the ldap backend, but I couldn't investigate more since I'm moving to a new place right now...

**Comment by jancborchardt** [comment]
@babelouest hope the move went fine! :) Any update on if it could cause problems with LDAP?

@blizzz please help here regarding testing with LDAP.

**Comment by babelouest** [comment]
I think this can be merged anyway, the change is too small to create other bugs I think, and the LDAP backend is still in beta mode so I'm OK with it.

**Comment by jancborchardt** [comment]
Nice, thank you @babelouest! :)

**Pull request merged**
