### PR TITLE
Manual Backport of #710

### PR DESCRIPTION
**Pull request by Gomez**
This is a manual backport of https://github.com/owncloud/contacts/pull/710

Cherry-pick or merge haven't worked for me (or i have done it wrong). 
Would be cool if someone approve or tell me how to do it right.

### CODE REVIEW

**Comment by Gomez** [comment]
@LEDfan can that be merged?

**Comment by LEDfan** [comment]
Thanks! @Gomez did you test this? I have to test this first too.

**Comment by Gomez** [comment]
Yes, its running on my server.

Would a git cherry-pick or merge possible, haven't got it right. Would be cool if you can try and gimme some advices.

**Comment by LEDfan** [comment]
Tested!

**Pull request merged**
