### PR TITLE
return 'PHOTO' attribute on AddressbookProvider::search

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #543

### CODE REVIEW

**Comment by jancborchardt** [comment]
Awesome! This fixes the Mail app not showing the actual contact pictures for me! :) :+1:

@DeepDiver1975 can you look at the Scrutinizer failure?

Please review @LEDfan @jbtbnl @babelouest :) (We should probably also backport this to stable7 afterwards.)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 can you look at the Scrutinizer failure?

That scrutinizer rule is a bit to aggressive - all reported Major issues are months/years old.
Sorry -> won't fix!

**Comment by tanghus** [comment]
> That scrutinizer rule is a bit to aggressive - all reported Major issues are months/years old.

My bad. I was a bit over-enthusiastic when writing scrutinizer rules.

**Comment by DeepDiver1975** [comment]
> My bad. I was a bit over-enthusiastic when writing scrutinizer rules.

no worries - the rules are interesting and would make sense in case scrutinizer would not create new issues on untouched/old code

**Comment by jancborchardt** [comment]
So, can we get this in? Please test @LEDfan @brantje @MorrisJobke :)

**Comment by jancborchardt** [comment]
This is tested and needed –> merging

**Comment by jancborchardt** [comment]
Backported: b8ad688

**Comment by DeepDiver1975** [comment]
grrr - this does break the search results for other properties -> revert

**Comment by jancborchardt** [comment]
The follow-up issue was fixed via https://github.com/owncloud/contacts/pull/569

**Comment by LEDfan** [comment]
I have an issue with fetching contacts from the Contacts app. Bitsec shows it's because of this commit. 
My code to fetch all contacst:

```
$cm = \OC::$server->getContactsManager();
$result = $cm->search('',array('FN'));
```

Which result in

```
[404] Contact not found

#0 /var/www/owncloud/apps/contacts/lib/addressbookprovider.php(117): OCA\Contacts\Addressbook->getChild('4')
#1 /var/www/owncloud/lib/private/contactsmanager.php(40): OCA\Contacts\AddressbookProvider->search('', Array, Array)
#2 /var/www/owncloud/apps/chat/core/appapi.php(78): OC\ContactsManager->search('', Array)
#3 /var/www/owncloud/apps/chat/controller/appcontroller.php(44): OCA\Chat\Core\AppApi->getContacts()
#4 [internal function]: OCA\Chat\Controller\AppController->index()
#5 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(155): call_user_func_array(Array, Array)
#6 /var/www/owncloud/lib/private/appframework/http/dispatcher.php(84): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Chat\Controller\AppController), 'index')
#7 /var/www/owncloud/lib/private/appframework/app.php(57): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Chat\Controller\AppController), 'index')
#8 /var/www/owncloud/lib/private/appframework/routing/routeactionhandler.php(44): OC\AppFramework\App::main('AppController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#9 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)
#10 /var/www/owncloud/lib/private/route/router.php(227): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)
#11 /var/www/owncloud/lib/base.php(714): OC\Route\Router->match('/apps/chat/')
#12 /var/www/owncloud/index.php(28): OC::handleRequest()
#13 {main}
```

When I change the search property from 'FN' to 'id', the code executes, but no contacts are fetched.
cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
I'll have a look - sorry for the mess. We better add unit test :wink:

**Comment by DeepDiver1975** [comment]
@LEDfan what was the result before that change? On current master the result is empty- right?

**Comment by LEDfan** [comment]
@DeepDiver1975 Now it seems like I only can fetch localusers Contacts via the ContactsManager. Contacts from the Contacts app are ignored....

**Comment by DeepDiver1975** [comment]
@LEDfan hmm - I need to get a better understanding of the issue.

How do the results look like before and after each individual change.
Because I never had a look at the contacts app up to now I need to ask that stupid question ;-)

**Comment by LEDfan** [comment]
@DeepDiver1975 looks like all issues are solved..... 
I can't reproduce my earlier problems. Both master and stable7 for both core and contacts.

**Comment by DeepDiver1975** [comment]
oh - great - THX

let me know in case you are running into issues again

**Pull request merged**
