### PR TITLE
User bower to load JS dependencies

### PR DESCRIPTION
**Pull request by jbtbnl**
Supersedes #703.

Please review @LEDfan @ockham

### CODE REVIEW

**Comment by ockham** [comment]
Works! :+1:

**Comment by ockham** [comment]
I'm in a merging mood, and is this is based on @LEDfan's work anyway, I'm assuming he'd agree to this.

**Comment by jbtbnl** [comment]
@ockham nice! Always good to see someone in a merging mood :smile:

**Comment by jbtbnl** [comment]
The squashed commit is on @LEDfan's name, so I suppose he is OK with it

**Comment by LEDfan** [comment]
Great!

**Pull request merged**
