### PR TITLE
fix excessive overwrite of mobile sizes defined in core, fix #555

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @owncloud/designers @stefan-niedermann @jbtbnl @LEDfan @babelouest

### CODE REVIEW

**Comment by jancborchardt** [comment]
We should also backport this later to stable7

**Comment by babelouest** [comment]
I don't know if I have small enough screens but this patch looks fine to me

**Comment by jancborchardt** [comment]
@babelouest just resize your browser window to test. ;)

**Comment by babelouest** [comment]
This is the smallest window size I can have on my laptop, looks good too :)

screenshot

**Comment by jancborchardt** [comment]
Yup – and now use the list icon (in the top left) for the sidebar, and check the settings menu on the bottom there if issue #555 is fixed by this. :)

**Comment by jancborchardt** [comment]
@owncloud/designers please check this out – it would be good if we can backport this to 7.0.1

**Comment by jancborchardt** [comment]
And backported as well: 23056e8

**Comment by babelouest** [comment]
I think we can close it now, what do you think ?

**Comment by jancborchardt** [comment]
@babelouest which issue / pull request are you talking about? ;) This has been merged in for some time already. :)

**Comment by babelouest** [comment]
well this one, the #556 :p

**Comment by jancborchardt** [comment]
So … it _is_ closed. ;) What are you talking about?

**Comment by babelouest** [comment]
my bad, it's a PR, not an issue :/

**Comment by jancborchardt** [comment]
Exactly. ;D

**Pull request merged**
