### PR TITLE
Added missing carddav routes.

### PR DESCRIPTION
**Pull request by boxdot**

### CODE REVIEW

**Comment by tanghus** [comment]
Thanks @finit-e 
Apparently I was a bit too fast when cleaning up some months ago :smile: 
Weirdly I have never had any problems while testing CardDAV. Did you get any errors?
Since public sharing isn't available for contacts I changed it manually in 6f683611310fd72234595227e1fb32c6b80fe339

**Comment by boxdot** [comment]
Carddav didn't work on my server, remote.php/carddav just stayed blank, no errors. Looking at the configuration in the databases revealed that there is no routing for carddav. I think the issue does not appear if you just upgrade your server and don't make a clean install.

**Comment by tanghus** [comment]
Ah yes, of course. I haven't done much testing from scratch recently. Nice catch, thanks again.

**Comment by filkeith** [comment]
Hi!
Have same problem

> Carddav didn't work on my server, remote.php/carddav just stayed blank, no errors.
> downloaded latest contact app and installed it, but nothing changed.

@finit-e 

> databases revealed that there is no routing for carddav
> How to fix it?

I have clear installed 6.0.0 beta, php 5.4.9, nginx. CalDav and WebDav working frine

**Comment by tanghus** [comment]
@filkeith Add the [highlighted lines](https://github.com/owncloud/contacts/commit/6f683611310fd72234595227e1fb32c6b80fe339) to `appinfo/info.xml`

**Comment by tanghus** [comment]
@filkeith And increment the number in `appinfo/version`. I think it's 0.2.81. Change that to 0.2.82.

**Comment by filkeith** [comment]
@tanghus 
that 2 lines are already there, as I said, I've downloaded latest version with that 2 lines.

When I increment version number all owncloud stops working. Blank screen everywhere.
And in nginx log errors:

> FastCGI sent in stderr: "PHP message: PHP Fatal error:  Using $this when not in object context in /var/www/owncloud/apps/contacts/appinfo/routes.php on line 14"

**Comment by tanghus** [comment]
@filkeith I take it you use PHP 5.3? This is solved by https://github.com/owncloud/contacts/pull/231
Change will be in beta 2/RC 1

**Comment by tanghus** [comment]
> /apps/contacts/appinfo/routes.php on line 14

Sorry, only just saw that it was in another place. That is a very weird error. Can you load ownCloud at all e.g. the files app?

**Comment by filkeith** [comment]
@tanghus 
I have php 5.4.9
And blank screen not in contacts only, whole owncloud stopped working. Blank screen on every page. Oh, will dig further, may be I'll find the problem
Thx, for fast response

When changed back to 0.2.81 owncloud works fine. Can't understand how its possible, but I haven't read apps dev documentation, may be I'm not understanding the architecture.

**Comment by tanghus** [comment]
@filkeith try to install xdebug so you can get a backtrace of the error

**Comment by filkeith** [comment]
@tanghus 
I've changed version number in appconfig table contacts installed version to 0.2.82 in database and owncloud starts working agian. But still no Card Dav access

**Comment by filkeith** [comment]
@tanghus 
So, problem was solved. I don't know what it was. I've disabled app and removed all records from database about contacts (3 tables and record in appconfig), then enabled it, and now everything working fine O_o

**Pull request closed without merging**
