### PR TITLE
Use correct method to extract image from vcard

### PR DESCRIPTION
**Pull request by tribut**
It was incorrectly assumed, that `$vcard` is always an `OCA\Contacts\Contact` (which is true when the contacts app is rendered) but when called from the `contactUpdated` hook, it actually is a `OCA\Contacts\VObject\VCard`.

Fixes owncloud/contacts#585

### CODE REVIEW

**Comment by jancborchardt** [comment]
@babelouest @ben-denham @ockham please review this :)

**Comment by jancborchardt** [comment]
@Larx @calleho can you test if this fixes https://github.com/owncloud/contacts/issues/585 for you?

**Comment by babelouest** [comment]
as well, quickly reviewed and tested, still no problem so I'm ok with this patch, thanks @tribut

**Comment by ockham** [comment]
I'm sorry, I can't say much about this as I don't have any failing use cases that are fixed by this PR.

**Comment by jbtbnl** [comment]
@tribut it would be nice if you could add some documentation to the function, with the appropriate types for the parameters specified!

**Comment by Ra72xx** [comment]
Unfortunately patch seems not to have been applied for 7.0.2.

**Comment by raoulbhatia** [comment]
seems to work for the owncloud instance i am using.

**Comment by Ra72xx** [comment]
I'm using ArchLinux packages for 7.0.2, and here the corresponding php-file definitely did not contain the necessary fixes. I had to add them manually.

**Comment by raoulbhatia** [comment]
FYI: I have been using this patch without any issues since my last post.

**Comment by Ra72xx** [comment]
Me too. Please include!

**Comment by jancborchardt** [comment]
Thank you for the reviews everyone! :)

If you want to help some more, check out the other pending pull requests: https://github.com/owncloud/contacts/pulls
And join us in #owncloud-contacts on IRC.

**Comment by Pazu** [comment]
@jancborchardt thanks for the merge! Can this be backported from master to stable7 for 7.0.3?

**Comment by jancborchardt** [comment]
@Pazu can you do a pull request for that? Simply change to the stable7 branch, cherry-pick this commit, and submit that. :)

**Comment by enoch85** [comment]
@PVince81 Could you fix the backport? We need this! Thanks :)

**Comment by jbtbnl** [comment]
Backported through https://github.com/owncloud/contacts/commit/509b4223ce382f5d70491defc741f61a07233870

**Comment by babelouest** [comment]
:+1:

**Comment by enoch85** [comment]
:+1: 

Close?

**Comment by raoulbhatia** [comment]
awesome - no need to track this out-of-upstream-patch anymore :+1:

**Pull request merged**
