### PR TITLE
Rename $this->tagMgr to $this->tags as that's what they are.

### PR DESCRIPTION
**Pull request by ockham**
They're instances of OCP\ITags, not of OCP\ITagManager.

### CODE REVIEW

**Comment by ockham** [comment]
@babelouest please review, this PR is a consequence of #584 and especially your #607 (see my comment there).

**Comment by ockham** [comment]
@danimo please review, this is a trivial amendment to your #584 which i just merged.

**Comment by ockham** [comment]
_ping_ guys, these are just variable renames, but as per owncloud policy, I need two positive reviews before merging, and @babelouest already wants these in the stable7 for 7.0.2. CCing @jancborchardt @MorrisJobke

**Comment by jbtbnl** [comment]
:+1:

**Pull request merged**
