### PR TITLE
Suppress sessions

### PR DESCRIPTION
**Pull request by Cymaphore**
Ability to supress session handling in dav requests, see https://github.com/owncloud/core/issues/5383 ... I would recommend to add this to the 5.x-fork as well.

### CODE REVIEW

**Comment by tanghus** [comment]
@DeepDiver1975 can you comment on this?

**Comment by DeepDiver1975** [comment]
@tanghus @Cymaphore let's discuss this in the scope of OC7 again - we shall focus now on oc6 release.
Once we agreed on a solution in OC7 backporting can be discussed as well.

**Comment by jancborchardt** [comment]
So let the discussion in the scope of ownCloud 7 begin.

**Comment by tanghus** [comment]
@DeepDiver1975 @jancborchardt @Cymaphore we're in the scope ;)

in the scope

**Comment by tanghus** [comment]
@Cymaphore Sorry but this has outlived itself. I appreciate taking up the issue. If it's still valid it would be great if you'd take it up again in core or on the mailing list.

**Pull request closed without merging**
