### PR TITLE
Bring back search functionality - fixes #335, #409, #792, #863, #961

### PR DESCRIPTION
**Pull request by DeepDiver1975**
@jancborchardt display of empty results looks odd - any ideas? THX

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
with some results:
bildschirmfoto von 2015-07-04 00-13-10

no results:
bildschirmfoto von 2015-07-04 00-10-41

**Comment by jancborchardt** [comment]
If there’s no results, then the list with contacts should not be shown. Only the »No search results in other places« #emptycontent thing. Then there’s also no overlap, and clear feedback.

**Comment by jancborchardt** [comment]
(Reviewing now)

**Comment by DeepDiver1975** [comment]
> If there’s no results, then the list with contacts should not be shown. Only the »No search results in other places« #emptycontent thing. Then there’s also no overlap, and clear feedback.

So we simply hide the list of all contacts? I question if click on a search result will continue to work ...

**Comment by DeepDiver1975** [comment]
Bäääh - one cannot hide a table?

**Comment by jancborchardt** [comment]
Should be possible. display:none or visibility:hidden, on the whole element. Or apply the class `.hidden-visually` to move it off the page.

**Comment by aspdye** [comment]
Any updates?

**Comment by jancborchardt** [comment]
cc @Henni @babelouest @jbtbnl

**Comment by DeepDiver1975** [comment]
TBH: I'd aim for 9.0 having carddav backend in core and a pure js based application - we will add proper search in there then

**Pull request closed without merging**
