### PR TITLE
Update search classes

### PR DESCRIPTION
**Pull request by abrown**
@tanghus, this is in reference to https://github.com/owncloud/core/pull/4553#issuecomment-30235122. Pretty similar to https://github.com/owncloud/calendar/pull/253.

### CODE REVIEW

**Comment by tanghus** [comment]
@andrewsbrown Great! I'll run it though it's paces tomorrow :)
Is this strictly oC7 or is a backport needed?

**Comment by abrown** [comment]
@tanghus, honestly I don't know... I'm using the 'update_search_classes' branch from owncloud/core and 'update_search_classes' from owncloud/contacts and they don't want to work together. I'm just not super-familiar with the ownCloud releases so maybe I'm just trying to mix and match wrong versions?

**Comment by jancborchardt** [comment]
@tanghus @andrewsbrown this is one of our oldest pull requests – any update on this? :)

**Comment by abrown** [comment]
@jancborchardt, I would close it: it was meant as a corollary to https://github.com/owncloud/core/pull/4553 and that never got any traction so I abandoned it several months ago.

**Comment by georgehrke** [comment]
@andrewsbrown 
The same as in calendar:
- [x] please use tabs instead of 4 spaces and
- [x] squash the commits

Do you have time to take care of this right now? If not just tell me and I'll take care
thx :)

**Comment by georgehrke** [comment]
fixes https://github.com/owncloud/contacts/issues/611

**Comment by abrown** [comment]
@georgehrke, it would be great if you could do it... I've been pretty busy with a new job.

**Comment by georgehrke** [comment]
@PVince81 @butonic @icewind1991 The same as in calendar :wink: 
 You reviewed https://github.com/owncloud/core/pull/4553, could you help to review this pr please :) thx

**Comment by icewind1991** [comment]
Code makes sense :+1:

**Comment by butonic** [comment]
:+1:

**Pull request merged**
