### PR TITLE
Fix 807 810

### PR DESCRIPTION
**Pull request by babelouest**
fixes small problems with import that were not detected before for some reason.

### CODE REVIEW

**Comment by gstuartj** [comment]
PR #816 is importing the home phone number field now, but it still seems to be missing mobile phone numbers. Also, if contact entries have multiple associated home phone numbers they are listed in one field separated by the string " ::: " rather than a comma like other import formats.

Address fields are also not parsed correctly and tend to have a lot of ", ::: ," delimiters sprinkled in.

**Comment by babelouest** [comment]
@gstuartj , it looks like other problems then, can you post new issues, one per problem so they can be better addressed ? If you comment this PR, the probability they are lost in the conversation are high...

**Comment by gstuartj** [comment]
Done.

**Comment by gstuartj** [comment]
#818 fixed by 8f29f21

**Comment by DeepDiver1975** [comment]
let me bring back ci - see #891 - then we add proper unit tests to this one an merge it

**Comment by DeepDiver1975** [comment]
@babelouest @gstuartj Any chance to get some sample file to be used as basis to build unit test? THX

**Comment by DeepDiver1975** [comment]
lets move this in :+1:

**Pull request merged**
