### PR TITLE
Upgrade max-version to 9.0 in appinfo

### PR DESCRIPTION
**Pull request by Henni**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by enoch85** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
meanwhile :-1: - sabredav classes need to be updated to make ti work in 9.0 again

**Comment by DeepDiver1975** [comment]
I'm closing this - starting with ownCloud 9.0 CalDAV and CardDAV are maintained within the core repo.

Feel free to submit a PR against core. THX

**Pull request closed without merging**
