### PR TITLE
Label style details

### PR DESCRIPTION
**Pull request by jancborchardt**
Some detail style fixes to the labels.

Before:
capture du 2015-07-02 20-41-07
After:
capture du 2015-07-02 20-41-49

Please review @DeepDiver1975 @owncloud/designers

### CODE REVIEW

**Comment by jancborchardt** [comment]
There’s a bunch of whitespace fixes which Atom did automatically – view the diff without whitespace changes at https://github.com/owncloud/contacts/pull/964/files?w=0

**Comment by jancborchardt** [comment]
Also cc @babelouest @derkostka for review. :)

**Comment by jancborchardt** [comment]
Also cc @babelouest @derkostka @tribut for review. :)

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
