### PR TITLE
Small fixes for header

### PR DESCRIPTION
**Pull request by jbtbnl**
Please review/thumbs up @owncloud/designers 
- Fixes header positioning when one or more contacts are selected
- Makes the sort selectbox reappear after deselection of contacts
- Removes some responsive leftovers that incorrectly positioned the header
- Fixes the column selection based on the screen width

### CODE REVIEW

**Comment by jbtbnl** [comment]
@ockham @SunboX it would be cool if you'd like to give this a spin and give your thumbs up!

**Comment by jancborchardt** [comment]
Great fixes! Tested and all work. :+1:

**Comment by jancborchardt** [comment]
We should also backport these fixes to stable7, right? @babelouest @jbtbnl what do you think?

**Comment by jbtbnl** [comment]
Yes, should be backported since they fix the export function and the styling of the header

**Comment by jancborchardt** [comment]
@jbtbnl do you want to do that? You know the `git cherry-pick` deal, right?

**Comment by jbtbnl** [comment]
Backported through https://github.com/owncloud/contacts/commit/822f4f108374e953b6e3f8e5402f364c3bc68bb7 https://github.com/owncloud/contacts/commit/78460dd17d43c42c7c8a4d85fe400b492f44d5c4 https://github.com/owncloud/contacts/commit/3a380f610adb94d1b9458c2b2a1899bcdcf9528e https://github.com/owncloud/contacts/commit/db9de23e77075de153faf3a92b6908131d3f1672

**Comment by raghunayyar** [comment]
\o/

**Pull request merged**
