### PR TITLE
7.0.2 rc2

### PR DESCRIPTION
**Pull request by babelouest**
I made this PR in order to test the last PRs in order to submit them in the next 7.0.2 release.
@ockham , @jancborchardt , @tribut , could you take a look if it's not too late ?

### CODE REVIEW

**Comment by jancborchardt** [comment]
@makuser @georgehrke @stephane84 @DeepDiver1975 @AdamWill you have commits in here, please test this backport as well.

**Comment by ockham** [comment]
@babelouest Are these exactly the commits from the PRs you mention at https://github.com/owncloud/contacts/commit/e822abd7e4b41d16e9f35b0377c3eb22fd4ae633#commitcomment-7459682 (or are there any others included, too?) If yes, I've commented [there](https://github.com/owncloud/contacts/commit/e822abd7e4b41d16e9f35b0377c3eb22fd4ae633#commitcomment-7500952).

**Comment by babelouest** [comment]
I think it would be better to skip 7.0.2 for these commits and review them properly, then merge into master, then in the stable branch, otherwise there will be too much rush...

**Comment by babelouest** [comment]
Rabased from master

**Comment by babelouest** [comment]
@ockham (or someone else) , do you have time to review and test this PR ?
I've rebased with mater rep so the merge will be easier.
Has branch stable7 been deleted ?

**Comment by jbtbnl** [comment]
@babelouest as far as I know the transifex updates are never merged in the stable branches after an ownCloud version is released.

Due to the nature of transifex, translations might disappear when they aren't necessary in master anymore and migt therefore break the stable branches if transifex updates are backported.

**Comment by babelouest** [comment]
I think this PR became too much troubled to merge it efficiently, I'll try to gather time this week to work on all of my unmerged PRs since 7.0

**Pull request closed without merging**
