### PR TITLE
Use thumbnail cache instead of refreshing every time

### PR DESCRIPTION
**Pull request by LEDfan**
There was a bug in the contacts app #741 
This means that every time the contacts app is loaded the cache was updated, instead of fetching the thumbnail from the cache.

@Gomez does this fix issue #741 and https://github.com/owncloud/chat/issues/173 + the slowness of the Chat app?

### CODE REVIEW

**Comment by Gomez** [comment]
Thanks @LEDfan. Slowness is gone, but avatar images (at least form oc users) are missing. I will test in deep later...

**Comment by LEDfan** [comment]
@Gomez do you mean avatars in the Chat app? Or in the Contacts app?

**Comment by Gomez** [comment]
In the chat app. I patched contacts stable7.

**Comment by LEDfan** [comment]
@Gomez an issue with the avatars in the Chat app should be fixed with https://github.com/owncloud/chat/commit/cec024116c069692b46bb0a47e7bc20eca5e8b3f .
You may have to run `localStorage.clear()` in the console of the browser + refresh.

**Comment by LEDfan** [comment]
@jbtbnl @babelouest please review :)

**Comment by Gomez** [comment]
Yes, fixed. Thanks!

:+1:

**Comment by babelouest** [comment]
I'm not sure I verified the new behaviour, but by appliying this patch, the thumbnails work fine. So that OK for me :)

**Comment by LEDfan** [comment]
@gomez I'll backport to stable7

**Comment by LEDfan** [comment]
Backported to stable7:
8e23084254614a12ab5b4deb56bc79ff364e4ecf
5dab5fd68c097658fde18c51b23ba2a9a65e4601

**Comment by babelouest** [comment]
:+1:

**Pull request merged**
