### PR TITLE
Added confirmation for deleting a addressbook #769

### PR DESCRIPTION
**Pull request by rehrumesh**
https://github.com/owncloud/contacts/issues/769

### CODE REVIEW

**Comment by ccoenen** [comment]
i would love to see this merged in. I just lost all of my contacts due to a missed tap on my mobile phone (delete instead of edit).

Luckily, i have a backup.

**Comment by babelouest** [comment]
@rehrumesh , I think the l10n files edition is not necessary, the translated strings are automatically parsed and added into the translation sub-project, so they can be easily translated into different languages and reinserted into the master branch through the owncloud-bot.

**Comment by babelouest** [comment]
@rehrumesh , I suggest changing the javascript confirm dialog by the owncloud confirm dialog, so it's more integrated: #794 , what do you think ?
@jbtbnl , @LEDfan , any feebback ?

**Comment by rehrumesh** [comment]
@babelouest That's a perfect improvement. With that the consistency of the app will be there. :) 
Can you have a look at issue #786 as well, because I think that issue is also occur due to the functionality of this function after deleting the self.

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/owncloud/contacts/pull/794 then :)

**Pull request closed without merging**
