### PR TITLE
Fix #880 #905

### LINKED ISSUE #880: Import fails: JSON.parse: unexpected character
When trying to import a Contacts.vcf I just exported from my ownCloud instance, I get this yellow notification error:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data: parsererror`

In the JS console:
```
"Import clicked" addressbooks.js:379:3
Object { readyState: 4, getResponseHeader: .ajax/C.getResponseHeader(), getAllResponseHeaders: .ajax/C.getAllResponseHeaders(), setRequestHeader: .ajax/C.setRequestHeader(), overrideMimeType: .ajax/C.overrideMimeType(), statusCode: .ajax/C.statusCode(), abort: .ajax/C.abort(), state: .Deferred/r.state(), always: .Deferred/r.always(), then: .Deferred/r.then(), 12 de plus… } storage.js:707:4
"jqXHR" Object { readyState: 4, getResponseHeader: .ajax/C.getResponseHeader(), getAllResponseHeaders: .ajax/C.getAllResponseHeaders(), setRequestHeader: .ajax/C.setRequestHeader(), overrideMimeType: .ajax/C.overrideMimeType(), statusCode: .ajax/C.statusCode(), abort: .ajax/C.abort(), state: .Deferred/r.state(), always: .Deferred/r.always(), then: .Deferred/r.then(), 12 de plus… } storage.js:12:2
"fail" Object { disabled: false, create: null, dropZone: Object, replaceFileInput: true, singleFileUploads: true, limitMultiFileUploadSizeOverhead: 512, sequentialUploads: false, forceIframeTransport: false, multipart: true, recalculateProgress: true, 46 de plus… }
```

And this in the owncloud.log
```
{"reqId":"ATvfOgsJxMq6L+3KZRJO","remoteAddr":"127.0.0.1","app":"no app in context",
"message":"Accessing the API class is deprecated! Use the appropriate services instead!",
"level":0,"time":"2015-04-15T20:20:42+00:00","method":"GET",
"url":"\/owncloud\/index.php\/apps\/contacts\/addressbooks\/"}
{"reqId":"jyp57Ts+Be+S1lEiMAAU","remoteAddr":"127.0.0.1","app":"no app in context",
"message":"Accessing the API class is deprecated! Use the appropriate services instead!",
"level":0,"time":"2015-04-15T20:20:48+00:00","method":"POST",
"url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/automatic\/import\/upload"}
{"reqId":"jyp57Ts+Be+S1lEiMAAU","remoteAddr":"127.0.0.1","app":"PHP",
"message":"Class 'OC_FileProxy' not found at \/home\/jan\/owncloud\/apps\/contacts\/lib\/controller\/importcontroller.php#89",
"level":3,"time":"2015-04-15T20:20:48+00:00","method":"POST",
"url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/1\/automatic\/import\/upload"}
```

@jbtbnl @babelouest @LEDfan any idea?

### PR DESCRIPTION
**Pull request by babelouest**
bugs with multiple values and parameters on import

### CODE REVIEW

**Comment by jancborchardt** [comment]
@babelouest ok, will need to test!

cc @DeepDiver1975 @jakobsack @nickvergessen @ockham please review as well! :)

**Comment by jancborchardt** [comment]
@babelouest I get `Internal Server Error: error` and this in the owncloud.log
```
{"reqId":"t5J1s+qC2gdy6SN7cc3J","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-11T09:57:59+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/3\/automatic\/import\/upload"}
{"reqId":"t5J1s+qC2gdy6SN7cc3J","remoteAddr":"127.0.0.1","app":"PHP","message":"Class 'OC\\NullCache' not found at \/home\/jan\/owncloud\/lib\/private\/server.php#221","level":3,"time":"2015-06-11T09:57:59+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/3\/automatic\/import\/upload"}
```

**Comment by nickvergessen** [comment]
@jancborchardt core issue: https://github.com/owncloud/core/pull/16872

**Comment by jancborchardt** [comment]
@babelouest great stuff, fixes the issue! :) :+1: 

A second review please! @DeepDiver1975 @jakobsack @nickvergessen @ockham @jbtbnl – also join our IRC channel #owncloud-contacts please everyone!

**Comment by jancborchardt** [comment]
(https://github.com/owncloud/contacts/issues/904 – missing pictures on import – still persists though ;)

**Comment by babelouest** [comment]
I know, I still suspect #904 isn't import related...

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
