### PR TITLE
fix #888 - $vevent was not initialized 

### LINKED ISSUE #888: DAVdroid sync is broken on Master - $vevent is not defined
Owncloud 8.1.alpha2 and Contacts-Master

I have exported all contacts from owncloud and imported them again, which worked well. Then i deleted all contacts on my Andorid device, they get synced 100% and then deleted again. The log is:

Log:
{"reqId":"VT6VXn8AAAEAAB0Msm4AAAAO","remoteAddr":"xxx","app":"PHP","message":"Undefined variable: vevent at \/var\/www\/owncloud\/apps2\/contacts\/lib\/contact.php#831","level":3,"time":"April 27, 2015 22:00:31"}
{"reqId":"VT6VXn8AAAEAAB0Msm4AAAAO","remoteAddr":"xxx","app":"PHP","message":"Call to a member function add() on a non-object at \/var\/www\/owncloud\/apps2\/contacts\/lib\/contact.php#831","level":3,"time":"April 27, 2015 22:00:31"}

Is this a DAVdroid issue or can somebody fix it here ? With OC 8.0 everything was perfect.

### PR DESCRIPTION
**Pull request by derkostka**
This commit is under the MIT license, you can use it for any purpose, of course !

### CODE REVIEW

**Comment by derkostka** [comment]
@raydiation: Still, the error is gone but all synced contacts are deleted again at the end on my device .. any idea how to debug ? Thanks!

**Comment by BernhardPosselt** [comment]
No idea would have to read into the code, not familiar with the code base

**Comment by derkostka** [comment]
I See, sorry ! So @LEDFan, maybe you know something / somebody who can test this. Thanks

**Comment by derkostka** [comment]
@PVince81 can somebody merge this one ? Should be in for 8.1 i suggest ...

**Comment by derkostka** [comment]
Ping ! @LEDfan  I guess we need something like that for 8.1, thanks !

**Comment by DeepDiver1975** [comment]
$event is also undefined - https://github.com/owncloud/contacts/pull/889/files#diff-bf9426f64760e23dbb062a5b191824dcR835

**Comment by jakobsack** [comment]
The second commit of this PR should get merged if it works as expected! The other changes have been applied by other PRs.

**Comment by derkostka** [comment]
Right, thank you. I removed the line in a new PR: #896  .. Please check and merge !

**Pull request closed without merging**
