### PR TITLE
Import from multiple formats

### PR DESCRIPTION
**Pull request by tanghus**
A cleanup and squash of #426

### CODE REVIEW

**Comment by tanghus** [comment]
@babelouest Here's the Scrutinizer report from the PR: https://scrutinizer-ci.com/g/owncloud/contacts/inspections/291e9347-94f7-4119-acfd-f608a1812b4f
You should subscribe to it to get reports automatically.
And the Travis report: https://travis-ci.org/owncloud/contacts/builds/20404005
There are no real integration tests yet though, so passing doesn't mean a lot ;)

**Comment by tanghus** [comment]
@babelouest For some odd reason the `'addressbook/{backend}/{addressBookId}/{importType}/import/upload'` request gets redirected to standard app. Nothing relevant in the logs.

**Comment by babelouest** [comment]
@tanghus ok, I'll take a look soon, thanks

**Comment by babelouest** [comment]
@tanghus , that's a tricky one, because of the new routes url construction, I can't understand why json returns the error so far...
I have checked the routes.php and it seems good, but the function in `addressbooks.js` returns an error when uploading the file (line 311 I think).
I'll look further when I'll have some time.

**Comment by tanghus** [comment]
I couldn't find the reason either. It shouldn't be much different from master.

**Comment by tanghus** [comment]
Argh, sometimes I have git!!!

**Comment by tanghus** [comment]
HATE!!

**Comment by tanghus** [comment]
And the saga continues in #444

**Comment by tanghus** [comment]
Sorry about that @babelouest - I don't know WTF I did wrong.

**Comment by babelouest** [comment]
It's ok, we'll fix it and then we'll see the light in the shadow ! ;)

**Comment by tanghus** [comment]
That's the spirit :smile:

**Pull request closed without merging**
