### PR TITLE
remove obsolete japanese lang code

### PR DESCRIPTION
**Pull request by vgezer**
Similar to https://github.com/owncloud/core/pull/10312.

We only have `ja.php` files. The other one is outdated.

### CODE REVIEW

**Comment by ockham** [comment]
+1
I've notice though that there's e.g. de_DE.php (in addition to de.php). What about that?

**Comment by ockham** [comment]
... or pl_PL.php? Looks like there might be some more examples...

**Comment by vgezer** [comment]
Ohh you are right. de_DE is for formal German, but pl_PL and zn_\* should be also removed I think. I will check them out. Thanks for noticing.

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
