### PR TITLE
Add avatar and placeholder JavaScripts

### PR DESCRIPTION
**Pull request by jbtbnl**
Fix for #592, please verify @monreal and @mroi

### CODE REVIEW

**Comment by jbtbnl** [comment]
cc @owncloud/designers, I'd like to merge this :)

Testing it is easy; enable/disable avatars in personal settings and see the result before and afterwards in the contacts app.

**Comment by jancborchardt** [comment]
Can’t test because Contacts stalls my ownCloud instance:

```
{"reqId":"614182343fb9cb959b083ecdc1089ddd","remoteAddr":"127.0.0.1","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 5\n)\n","level":0,"time":"2014-10-08T11:01:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/indexproperties\/%7Buser%7D\/"}
{"reqId":"614182343fb9cb959b083ecdc1089ddd","remoteAddr":"127.0.0.1","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 5\n)\n","level":0,"time":"2014-10-08T11:01:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/indexproperties\/%7Buser%7D\/"}
{"reqId":"614182343fb9cb959b083ecdc1089ddd","remoteAddr":"127.0.0.1","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 6\n)\n","level":0,"time":"2014-10-08T11:01:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/indexproperties\/%7Buser%7D\/"}
{"reqId":"614182343fb9cb959b083ecdc1089ddd","remoteAddr":"127.0.0.1","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 6\n)\n","level":0,"time":"2014-10-08T11:01:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/indexproperties\/%7Buser%7D\/"}
{"reqId":"614182343fb9cb959b083ecdc1089ddd","remoteAddr":"127.0.0.1","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 7\n)\n","level":0,"time":"2014-10-08T11:01:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/indexproperties\/%7Buser%7D\/"}
{"reqId":"614182343fb9cb959b083ecdc1089ddd","remoteAddr":"127.0.0.1","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 7\n)\n","level":0,"time":"2014-10-08T11:01:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/indexproperties\/%7Buser%7D\/"}
{"reqId":"614182343fb9cb959b083ecdc1089ddd","remoteAddr":"127.0.0.1","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 8\n)\n","level":0,"time":"2014-10-08T11:01:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/indexproperties\/%7Buser%7D\/"}
{"reqId":"614182343fb9cb959b083ecdc1089ddd","remoteAddr":"127.0.0.1","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 8\n)\n","level":0,"time":"2014-10-08T11:01:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/indexproperties\/%7Buser%7D\/"}
{"reqId":"614182343fb9cb959b083ecdc1089ddd","remoteAddr":"127.0.0.1","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 9\n)\n","level":0,"time":"2014-10-08T11:01:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/indexproperties\/%7Buser%7D\/"}
{"reqId":"614182343fb9cb959b083ecdc1089ddd","remoteAddr":"127.0.0.1","app":"contacts","message":"OCA\\Contacts\\Utils\\Properties::purgeIndexes, ids: Array\n(\n    [0] => 9\n)\n","level":0,"time":"2014-10-08T11:01:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/indexproperties\/%7Buser%7D\/"}
```

**Comment by MorrisJobke** [comment]
> Can’t test because Contacts stalls my ownCloud instance:

Same here

**Comment by jbtbnl** [comment]
Please review @hostingnuggets and @sorglos

**Comment by hostingnuggets** [comment]
@jbtbnl I manually patched the pagecontroller.php file and it works for me, cheers! Would be great if you can include this PR into OC 7.0.3.

**Comment by jbtbnl** [comment]
OK, merging it now in the hope that it will make OC 7.0.3

**Comment by ghost** [comment]
@jbtbnl :+1: .

**Comment by jbtbnl** [comment]
Backported through https://github.com/owncloud/contacts/commit/b9c100c60516a6715c472239c3794c6940b459de

**Comment by jbtbnl** [comment]
@sorglos thanks for your feedback :)

**Pull request merged**
