### PR TITLE
fix bug #488

### PR DESCRIPTION
**Pull request by babelouest**
to be able to import in different addressbooks without having to reload the page

### CODE REVIEW

**Comment by babelouest** [comment]
@jbtbnl , this is another bug that is related to import as well. I made another PR for the stable7 branch (#736) because master and stable7 branches are quite different now in this part of the application.

**Comment by jbtbnl** [comment]
@babelouest I did a quick search to see what the function variable `getStatus` is used for, but I can not find any occurrences of it, except for the definition. So I assume we can delete https://github.com/owncloud/contacts/blob/import-different-addressbooks/js/addressbooks.js#L537

`interval` variable is unused as well:
https://github.com/owncloud/contacts/blob/import-different-addressbooks/js/addressbooks.js#L529

**Comment by babelouest** [comment]
That's possible, I'll test the suppression when I'll have a minute, thanks :-)

Although, one thing I have in my TODO list is to completely rewrite the javascript import UI part.
When I implemented the multi-format, I adapted the existing import UI which already was an modification of a previous import UI, so the technical debt is huge and makes bugs like this one difficult to find and to clean.

**Comment by babelouest** [comment]
@jbtbnl , in the stable branch, the getStatus function is used in an interval: https://github.com/owncloud/contacts/blob/import-different-addressbooks-stable/js/addressbooks.js#L538
That's probably an unfinished cleanup in the master branch.

Anyway, I think this would be better to make another PR for the getStatus thing, I'd like to merge this PR and the stable one too for the next release, this bug is here for too long...

**Comment by jbtbnl** [comment]
@babelouest agreed, we need to push fixes before oC 8 :+1:

**Comment by babelouest** [comment]
:+1: 
I understand that the stable branch is deprecated since oc8 is in alpha mode and based on the master branch, so no need for #736, right ?

**Comment by jbtbnl** [comment]
@babelouest it is up to us and the community how long we want to push fixes to stable7.

**Comment by babelouest** [comment]
@jbtbnl , you're right, no need to remove this PR.

**Pull request merged**
