### PR TITLE
Upgrade max-version to 9.0 in appinfo

### PR DESCRIPTION
**Pull request by Henni**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
We also need to adjust travis.yml which tries to test against 8.1

**Comment by Henni** [comment]
BTW: contacts currently doesn't work on 9.0 as the dav code in core changed. So maybe we should wait with updating the info.xml

**Comment by DeepDiver1975** [comment]
:-1: the app will not work in oc 9.0

**Pull request closed without merging**
