### PR TITLE
fix bug with colon and space in vcard import

### PR DESCRIPTION
**Pull request by babelouest**
fix bug with colon and space that made the import controller guess it's a ldif file instead of a vcard...

### CODE REVIEW

**Comment by babelouest** [comment]
@jbtbnl , permission to merge in stable7 for 7.0.4 ?

**Comment by jbtbnl** [comment]
@babelouest is this a fix for https://github.com/owncloud/contacts/issues/713? If so, has this been tested by @daald? 

I think we should backport this indeed.

**Comment by daald** [comment]
I don't know if it was developed explicitly for this bug, but I confirm this patch solves #713.

**Comment by jbtbnl** [comment]
This PR [has been reported](https://github.com/owncloud/contacts/issues/542#issuecomment-65965955) to fix #542 as well, good job @babelouest !

**Comment by babelouest** [comment]
This can be backported to stable7 as well, unless you prefer it to be released in 7.0.5

**Comment by jbtbnl** [comment]
Backported through https://github.com/owncloud/contacts/commit/4ebbf1ceed51ea412bc90e60b77c50996548fc51 and https://github.com/owncloud/contacts/commit/65bca0269fa86e6f87211caf69f2de3ac972f1ec

**Comment by babelouest** [comment]
:+1:

**Pull request merged**
