### PR TITLE
Fix loading of migration provider class

### PR DESCRIPTION
**Pull request by tomneedham**
Change the loading of the migration provider to load it in the proper namespace.

@bartv2 @tanghus

### CODE REVIEW

**Comment by tanghus** [comment]
Thanks. Do you backport it now you're there? ;)

**Comment by tomneedham** [comment]
Sure

**Comment by tomneedham** [comment]
Done: https://github.com/owncloud/contacts/commit/012e82f11c65a83dab3b37bb2dcfbd67e4e6f1b6

**Comment by tanghus** [comment]
:beers:

**Pull request merged**
