### PR TITLE
fix bug #498

### PR DESCRIPTION
**Pull request by babelouest**
A quick change to fix the issue #498.

### CODE REVIEW

**Comment by requist** [comment]
Tested and works OK here. :+1:

**Comment by babelouest** [comment]
Worked here too with the local and ldap backend, I'm merging

**Comment by GenXRoad** [comment]
Hello, i tested the master, the last dayly build, i even get an errorr on line 64 dispatcher.php so the contacts app will result in 500 internal Server error, which branch will corect  work?

**Comment by babelouest** [comment]
@GenXRoad , are you using the last commit ? I don't get any error with the last one: https://github.com/owncloud/contacts/commit/f6804bac154715cf680804c7d4cb681d510bc651

**Comment by GenXRoad** [comment]
Jes, i' running oc 7 pre alpha since 1 werk dayly upload the new dayly build but since the ldap merg dispatcher.php won't work. I don't know if some files missing? Because clean install oc 7 , the error message i can post later, i'm currenty only with my mobile phone online

**Comment by LEDfan** [comment]
There is a bug in the dispatcher class for PHP 5.3. `$this` should be changed in `$container` Therefore https://github.com/owncloud/contacts/blob/master/lib/dispatcher.php#L87

Refs #481

**Comment by GenXRoad** [comment]
Thank you LEDfan, i will test it today

**Comment by GenXRoad** [comment]
Now it will work, but now an template is missing contacts:formfactor

**Comment by LEDfan** [comment]
@GenXRoad I will fix the PHP 5.3 errors.

**Comment by LEDfan** [comment]
@GenXRoad can you test 0e863592e616a10893c13e26d1844cf1ce21c80b ? It should be solved now.

**Comment by GenXRoad** [comment]
Thank you, tested it localy, will work, on my root i made distro upgrade to newest version with php 5.4

**Pull request merged**
