### PR TITLE
Shorten display of contact's birthdays in Calendar

### PR DESCRIPTION
**Pull request by deMattin**
Replaces "birthday" with a UTF8 birthday cake;
works language independend;
also synchronizes well to PC and smartphone/tablet
https://github.com/owncloud/contacts/issues/1027

### CODE REVIEW

**Comment by deMattin** [comment]
If integration is accepted by core team, it can also simply be backported to stable 8.1.
(I would make a pull request then, if desired)

**Comment by jancborchardt** [comment]
@babelouest @LEDfan @jbtbnl @schiesbn please review! :)

**Comment by DeepDiver1975** [comment]
Is this 4 byte string stored in the db? If yes we cannot do this - mysql only allows 3byte chars (the way we use it)

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2015-10-12 14-01-18

bildschirmfoto von 2015-10-12 14-01-36

**Comment by DeepDiver1975** [comment]
I'm honestly not really impressed by this

**Comment by jakobsack** [comment]
I agree with Thomas, I don't like the cake symbol either.

If it is necessary to shorten the birthday entries I'd rather use the star (*) which is not only a ASCII sign but also widely recognized as a symbol for the date of birth. It could look like `Jakob Sack (*1986)`. But that's just my point of view.

**Comment by deMattin** [comment]
Replacing the cake with a star at the year is ok, also.
Everything cutting off "Geburtstag von ..." is better than it is actually!
Many people like to shorten this as you can see in the issue discussion..
@DeepDiver1975 please rethink about shorting this.and implement it in a way you like.

**Comment by DeepDiver1975** [comment]
I'm closing this - starting with ownCloud 9.0 CalDAV and CardDAV are maintained within the core repo.

Feel free to submit a PR against core. THX

**Pull request closed without merging**
