### PR TITLE
- replace numRows() calls

### PR DESCRIPTION
**Pull request by DeepDiver1975**
- fixing some namespace and syntax issues

@tanghus

### CODE REVIEW

**Comment by tanghus** [comment]
Awesome, thanks a lot :) I had made a reminder to myself in #317 but hadn't gotten around to it.

**Comment by jancborchardt** [comment]
@tanghus @jbtbnl can you review this? Thx! :)

**Comment by jbtbnl** [comment]
:+1:

**Comment by jancborchardt** [comment]
@tanghus did you test and review this as well?

**Comment by jancborchardt** [comment]
@babelouest can you review this and merge if it’s good?

**Comment by tanghus** [comment]
:+1:

**Pull request merged**
