### PR TITLE
fix TagMgr access remove unwanted error_log

### PR DESCRIPTION
**Pull request by danimo**
We just noticed that this was missing in stable7 and caused an import error.

### CODE REVIEW

**Comment by mutax** [comment]
It applied to 7.0.1 (stable) and the internal server error on importing is gone. Seems to work. Thanks!

**Comment by jancborchardt** [comment]
Can you review this @babelouest @ockham?

**Comment by ockham** [comment]
I can confirm that on the stable7 branch, importing my test *.csv file fails halfway, while with the backport-fix-TagMgr-access branch it works. So merging is fine with me!

**Comment by babelouest** [comment]
I tested the fix and all my import still pass, merging is fine with me too

**Comment by ockham** [comment]
Okay, merging as there are two positive reviews (including mine) and _because I can_ :-) (I've asked on #owncloud-dev yesterday, but no response. Still hope it's fine.)

**Pull request merged**
