### PR TITLE
fix for https://github.com/owncloud/contacts/issues/537

### PR DESCRIPTION
**Pull request by babelouest**
https://github.com/owncloud/contacts/issues/537

### CODE REVIEW

**Comment by jancborchardt** [comment]
@babelouest what to do with this pull request? :) Is it a fix for #537 and ready to be reviewed?

**Comment by babelouest** [comment]
yes, this is a fix for #537, I accidently committed disabling import contact files from the files app in this PR. Anyway I retested this fix in a merge from v7.0.1RC1 and it still works for me, can you review the code so it could be in 7.0.1 release ?

**Comment by jancborchardt** [comment]
@emc02 @Larx please test if this fixes https://github.com/owncloud/contacts/issues/537 for you.

**Comment by Ra72xx** [comment]
Quick test with a single contact.vcf - importing multiple categories seems to work with this fixes.

**Comment by jancborchardt** [comment]
@Larx thank you!

@emc02 can you please also test? :)

**Comment by emc02** [comment]
I try to test it today, but it ia my first time adding a fix to something, so I have to first check gow to do this ;-)

**Comment by jancborchardt** [comment]
@emc02 if you have any questions, you are very welcome in our IRC channel #owncloud-dev – there’s lots of people who can help you set ownCloud up for testing. :)

**Comment by emc02** [comment]
edited the files by myself ;)
Import of google.csv file with for example 12 contacts is working perfect now.

On importing all of my contacts (1400) once, all Groups are shown with the correct number of contacts inside, but the contacts are not shown in web interface because it shows only the loading symbol (more than 5 minutes).
Without the fix it  showed contacts after max 30 seconds.

I reverted the changes after importing, but its also not showing the contacts. But importing seems to work correct, because all contacts are synced to my Android phone.

**Comment by emc02** [comment]
found another Problem and wondering why nobody else found that: Phone Numbers are not importet to my contacts from google.csv file. All my phone Numbers start with +43, maybe thats a reason?!

**Comment by babelouest** [comment]
already merged in #642

**Comment by jancborchardt** [comment]
(@babelouest remember to delete unneeded branches then ;) just did it with this one.)

**Pull request closed without merging**
