### PR TITLE
Display correct number of contacts in shared addressbooks.

### PR DESCRIPTION
**Pull request by ockham**
Fixes #654.

Please review @jbtbnl @nexusnetwork23 !

### CODE REVIEW

**Comment by jbtbnl** [comment]
Nice! Tested, works well :+1:

**Comment by ockham** [comment]
@jbtbnl Thx for the review!

Let's CC some more folks: @babelouest @LEDfan @AnybodyElse @Raydiation @DeepDiver1975

**Comment by ockham** [comment]
CCing @MorrisJobke @LukasReschke 

Simple bug fix here!

**Comment by ockham** [comment]
Given that currently it's very hard to attract more reviewers, and following discussion on `#owncloud-dev` where it was stated that two reviewers were a hard requirement only for core but not necessarily for apps as long as all app maintainers agreed, I'm merging this.

As the Contacts app currently doesn't really have any actual maintainers, with only @jbtbnl (who has :+1:'d this PR) and myself being the most active devs, I take it as concludent that it's okay to do so.

**Comment by jbtbnl** [comment]
@ockham totally agree!

**Comment by MorrisJobke** [comment]
@ockham Yes. Thanks for your work :)

**Pull request merged**
