### PR TITLE
Fix multi version and only upgrade 2.1 cards.

### PR DESCRIPTION
**Pull request by gvde**
Backport of #1054 
Make sure to replace PRODID and VERSION instead of adding
additional ones...

Only upgrade a vcard to 3.0 if it is 2.1.
Only set REV if something has been repaired.

If multiple VERSION values are set, remove all and set only the value
of the first.
If card has been repaired change PRODID to own appinfo.

satisfy Scrutinizer

### CODE REVIEW

**Comment by h-2** [comment]
Yes, this fixes my problems, please merge it :+1:

**Comment by ColinFinck** [comment]
Just upgraded from ownCloud 8.1.3 to 8.2.0 in the hope to fix issue #1007 (aka #994), but was shortly disappointed afterwards when noticing that my Contact photos were still being deleted. I'm successfully running an ownCloud installation with the Contacts app since 6.x and the aforementioned bug destroys most of the great experience.

Manually applying the patch provided here solves the problem.
Please merge this back and backport the fix as soon as possible to all supported versions and provide new stable releases.
It would be a disaster if even more people running the latest stable ownCloud version lose parts of their Contact database due to this nasty bug.

**Comment by KekcuHa** [comment]
I have applyed provided patch on OC 8.2.2 and it solved the problem of the sync android contacts with photos.
gvde, thank you very much!

**Comment by h-2** [comment]
What is preventing this from being merged? Isn't like everyone affected?

**Comment by gvde** [comment]
There is no maintainer of this app. Thus is takes a while until someone else does the merge.

**Comment by fossxplorer** [comment]
I can do the merge since others have tested the PR. Is it OK?
What about backport to stable8.2?

**Comment by tribut** [comment]
:+1:

**Comment by gvde** [comment]
master PR is #1054 
stable8.2 PR is #1068

**Comment by kallegit1950** [comment]
I have tested #1068 on my OC installation and it fixes an issue that a sync via DavDroid removes attached photos.

**Comment by fossxplorer** [comment]
@gvde Travis CI fails on https://github.com/owncloud/contacts/pull/1054, but https://github.com/owncloud/contacts/pull/1068 is now merged.

**Comment by gvde** [comment]
@fossxplorer just rerun travis for #1054 and it passes now... (It failed in October, because core was on 9.0 but contacts app master was not compatible set to be compatible with 9.0...)

**Comment by fossxplorer** [comment]
@gvde 1054 merged. Thx a lot for your help!

**Pull request merged**
