### PR TITLE
update SabreDAV to 1.8.10

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by jbtbnl** [comment]
@DeepDiver1975 has this been tested already, can it be merged?

**Comment by DeepDiver1975** [comment]
@jbtbnl this needs testing - but because we merged sabre-dav in core this can be merged as contacts/master will not work either

**Comment by requist** [comment]
Works for me, however it does give me an error which might be related:

`{"app":"PHP","message":"Call to undefined method OCA\\Contacts\\VObject\\VCard::getPhoto() at \/usr\/share\/owncloud\/apps\/contacts\/lib\/utils\/properties.php#314","level":3,"time":"June 12, 2014 22:15:04"}`

**Comment by babelouest** [comment]
I Don't know if it's related to SabreDAV update, but using current master branch, I have the following error when I access the CardDAV backend:
`PHP Fatal error:  Class 'Sabre_CardDAV_Backend_Abstract' not found in [...]/owncloud-master/contacts/lib/carddav/backend.php on line 36`

**Comment by requist** [comment]
@babelouest Yes, that is related, see: https://github.com/owncloud/core/issues/9011

**Comment by jbtbnl** [comment]
Contacts master needs to work with the upcoming alpha's and beta's so let's merge this and handle bugs in separate issues!

**Comment by jancborchardt** [comment]
@jbtbnl you can safely delete branches which have been merged by the way. :) Just press the »delete branch« button. (I did this now.)

**Pull request merged**
