### PR TITLE
Fix vendor_script not found

### PR DESCRIPTION
**Pull request by LEDfan**
Fixs #727 
Note that this issue only happens when you are using `master` contacts and `stable7` ownCloud.

### CODE REVIEW

**Comment by jbtbnl** [comment]
cc @Raydiation @MorrisJobke, I don't think it is desirable to have such patches in apps. Either core should provide a fallback, or we should accept that the master branch is incompatible with stable7, which is likely the case anyway.

**Comment by BernhardPosselt** [comment]
Doing the same here: https://github.com/owncloud/news/blob/master/templates/index.php#L12

:+1:  from my side :)

**Comment by BernhardPosselt** [comment]
You could ofc create a separate app which includes backports but then all hell will break loose with people going ermagerd noes app derperndencies

**Comment by jbtbnl** [comment]
@LEDfan this PR conflicts with your point of view at https://github.com/owncloud/contacts/pull/725#issuecomment-65752970

**Comment by LEDfan** [comment]
@jbtbnl you are right. I created this PR because someone in the mailing list was using OC7.0.3 and Contacts master

**Comment by jbtbnl** [comment]
@LEDfan yeah, anytime soon there should be support in Core for specifying dependencies for apps. Until then we'll stick to single version compatibility and backports for bugs.

**Pull request closed without merging**
