### PR TITLE
migrate OC::session to OC::server->getSession

### PR DESCRIPTION
**Pull request by MorrisJobke**
Fixes #716

@babelouest @jbtbnl

### CODE REVIEW

**Comment by MorrisJobke** [comment]
ref owncloud/core#10793

**Comment by jbtbnl** [comment]
:+1: thanks!

**Comment by MorrisJobke** [comment]
No problem :) We need to support you community contributors. You do great work, and I just try to help you were I can.

**Comment by LukasReschke** [comment]
By the way if you use the AppFramework with master/oC8 there is no need anymore to close the session manually. The AppFramwork will close the session for you if no `@UseSession` annotation have been found on the controller.

**Pull request merged**
