### PR TITLE
Update contacts.css - fixes #823 (no sparate input fields for contact na...

### LINKED ISSUE #823: ownCloud 8 Contacts 0.3.0.18: name editing problem (caused by CSS)
I have just upgraded to ownCloud 8.0, and have noticed a problem with the Contacts app (version 0.3.0.18):

When editing a contact, the pen next to the full „Name“ text input field does not appear anymore when hovering over the field (as it did in earlier versions), therefore it is not possible to get to the text input fields for „First name“, „Additional names“ and „Last name“.

I have checked with IE11 (most up to date version) and Chrome browsers on Windows 8.1 x64, the problem occured in both of them.

As a quick fix, adding the following line to the contacts.css solved the problem for me (but perhaps there is another solution):
.singleproperties .icon-rename { position:absolute; }

### PR DESCRIPTION
**Pull request by deMattin**
...mes)

Issue reported including the fix in https://github.com/owncloud/contacts/issues/823 by @eckelmi.

In OC 8.0 it's not possible to get to the text input fields for "First name", "Additional names" and "Last name" because the pen symbol is missing next to the full name.
This fix adresses this problem and solves it with the additional css definition.

### CODE REVIEW

**Comment by deMattin** [comment]
Travis CI test failes because the testing routine has errors?!

**Comment by LEDfan** [comment]
Don't mind the falling unit tests for this PR. Thanks for you patch. I confirmed the bug and the patch works!

**Comment by ghost** [comment]
Hi,

it seems to late for OC 8.0.3 but what about a backport to OC 8.0.4?

**Comment by deMattin** [comment]
Do you think, there'll ever be a 8.0.4?
Actual status:
8.1-current: Past due by 21 days (85% complete  155 open  882 closed)
8.0.3-current-maintenance: Past due by 17 days (100% complete  0 open  73 closed)

The new release schedule strategy as described doesn't seem to work or to be taken  : https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule
`Each year there will be four major ownCloud versions: x.0 will be released in Q1 (~ End of January), x.1 in Q2 (~ End of April), x.2 in Q3 (~ End of July) and x.3 in Q4 (~ End of October).`

Simple use a theme to patch css and change the setting there or patch the original file, if you don't use theming at all.
That's how I do it (use theming) and also fix some other problems, because it lasts very long, til a simple fix like this is seen by user in a release version.

**Comment by ghost** [comment]
Hi,

i don't have any problems doing this patch but had a question at the forums about this missing edit button. Not everyone out there is checking the bugtracker for possible fixes. :wink: Thats why i have asked for a backport.

**Pull request merged**
