### PR TITLE
fix birthday calendar

### PR DESCRIPTION
**Pull request by georgehrke**
please review @DeepDiver1975 @jancborchardt 

this also needs to be back ported to stable8.1

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
> this also needs to be back ported to stable8.1

please submit pr against stable8.1 as well
 THX

**Comment by georgehrke** [comment]
here you go: https://github.com/owncloud/contacts/pull/971

**Comment by MeCias** [comment]
https://github.com/owncloud/calendar/issues/824#issuecomment-118983847

**Comment by askovpen** [comment]
plz push it to https://github.com/owncloud/calendar/tree/stable8.1

**Comment by georgehrke** [comment]
There already is a pr for backporting, which I just mentioned two comments above your's https://github.com/owncloud/contacts/pull/971

**Comment by raimund-schluessler** [comment]
Fixes the issue, so :+1:

**Comment by nRaecheR** [comment]
This fix causes a high load on the Owncloud server and Android clients with CalDAV app and a lot of bandwidth usage on my mobile device. It seems the sync will never finish and gets into an endless loop. Here's a part from the Apache2 log file : 

```
10.42.0.6 - test_user [10/Sep/2015:10:39:29 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 71290 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:39:41 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 69866 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:39:56 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 67362 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:42:26 +0200] "PROPFIND /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 7078 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:42:26 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 46456 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:42:38 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 68361 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:42:53 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 28148 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:47:24 +0200] "PROPFIND /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 7078 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:47:24 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 71290 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:47:36 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 69866 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:47:52 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 67362 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:50:27 +0200] "PROPFIND /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 7078 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:50:27 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 46456 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:50:41 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 68361 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:50:56 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 28148 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:55:25 +0200] "PROPFIND /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 7078 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:55:26 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 71290 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:55:38 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 69866 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:55:53 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 67362 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:59:14 +0200] "PROPFIND /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 7078 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:59:15 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 46456 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:59:28 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 68361 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:10:59:56 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 28148 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:11:02:00 +0200] "PROPFIND /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 7078 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:11:02:01 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 46456 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:11:02:13 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 68361 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:11:02:29 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 28148 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:11:04:40 +0200] "PROPFIND /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 7078 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:11:04:41 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 46456 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:11:04:55 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 68361 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
10.42.0.6 - test_user [10/Sep/2015:11:05:12 +0200] "REPORT /remote.php/caldav/calendars/test_user/contact_birthdays/ HTTP/1.1" 207 28148 "-" "CalDAV-Sync/0.4.27 (samsung; jfltexx; Android 5.0.1; de_DE; org.dmfs.caldav.lib/732; like iOS/5.0.1 (9A405) dataaccessd/1.0)"
```

The Owncloud own log file is empty. 
Removing the one line patch fixes the loop, the high load on server and clients, but the birthday events disappear again. 
It seems to work with other clients (KDE Kontacts, Gnome Evolution, DAVDroid ) without that problem, but it worked with pre-8.x Owncloud server without problems with this sync client. 

Tested with Owncloud 8.1.2, CalDAV 0.4.27 on Android 5.0.1 and on another device with Android 5.1.1. 

@georgehrke Any thoughts ?

**Comment by gvde** [comment]
@nRaecheR fixed in #1005

**Comment by nRaecheR** [comment]
@gvde Yes, I've applied the patch and the load and bandwidth usage dropped to normal. Thank you !

**Pull request merged**
