### PR TITLE
[WIP] Fix double-encoding bug

### PR DESCRIPTION
**Pull request by untitaker**
This is work-in-progress, I couldn't find any resources on how to run the unit tests locally so I'm just gonna do it "in the cloud".

Fixes https://github.com/owncloud/contacts/issues/581

### CODE REVIEW

**Comment by untitaker** [comment]
I don't know how to test this since the backend seems to be stubbed out with a mock?

**Comment by untitaker** [comment]
I'm sort-of giving up on the tests. If somebody sets up a basic testsuite for the SabreDAV backend, I'm willing to rebase this PR and add a test for the particular bug I'm trying to fix. At the moment this would require knowledge of ownCloud's internals I don't have (and don't care about).

**Comment by onny** [comment]
This fix does not resolve https://github.com/bitfireAT/davdroid/issues/578 issue for me :(

**Comment by onny** [comment]
Ups sorry, was my mistake. This is working perfectly, thanks!

**Comment by nullspoon** [comment]
Just another verification here. Tested the change for _lib/carddav/backend.php_ on **Owncloud 8.2** and **Contacts 0.4.0.0** and issue bitfireAT/davdroid#578 was resolved. Thanks for doing this untitaker! Tests or no, glad to be up and running again.

**Comment by BernhardPosselt** [comment]
Thanks for the work, the builds are broken in general and there needs to be done a lot of work to get tests running in general. I've only taken your one line fix and pushed to master, since this seems to go nowhere :)

**Pull request closed without merging**
