### PR TITLE
Fix photo import

### LINKED ISSUE #904: Import does not import profile image
I have a vcf file with a bunch of contacts, most of them with user image. None of them is imported.

This is an example of the exported file, only the photo portion: https://cloud.jancborchardt.net/public.php?service=files&t=6370883caffc4a986fc9ef5315b1ffc5 (beautiful face of @DeepDiver1975 ;)

As you can’t see, you can’t see anything:
capture du 2015-05-19 16 08 36

@babelouest @jbtbnl @LEDfan

### PR DESCRIPTION
**Pull request by DeepDiver1975**
fixes #904 #878 

@jancborchardt @LEDfan please test - THX

### CODE REVIEW

**Comment by jancborchardt** [comment]
@DeepDiver1975 as said in #904 I think the import was done from my productive ownCloud 7 instance. Do I need to apply the patch there, or to the instance I want to import to?

**Comment by DeepDiver1975** [comment]
Patch is for 8.1 only - so on import .... but give me a second to test this once more.

**Comment by DeepDiver1975** [comment]
Okay - I only fixed setting/uploading of an image ....

**Comment by DeepDiver1975** [comment]
@jancborchardt here we go

**Comment by jancborchardt** [comment]
Nice! This fixes the photos in the Mail app and in the detail view of the contacts app. However, they are still not shown in the list view of the contacts app.

These are the errors when opening the Contacts app:

```
{"reqId":"8oD4\/6sr\/MVyXVBrNO\/s","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:47+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/"}
{"reqId":"A9jmyJhOywEJ30KhOpXe","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:50+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/connectors\/%7Bbackend%7D"}
{"reqId":"a2uTfHPSzzaFeZZQz7SW","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:50+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/groups\/"}
{"reqId":"OOJc3CHou0yBRVfGyBxO","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:50+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbooks\/"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:50+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"a2uTfHPSzzaFeZZQz7SW","remoteAddr":"127.0.0.1","app":"core","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>!$_\"","level":0,"time":"2015-06-30T12:39:50+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/groups\/"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/jan\/owncloud\/lib\/private\/image.php#622","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2015-06-30T12:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}
{"reqId":"b\/mWkSzRsJ3QGEESFBEC","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:55+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/contacts\/preference\/set"}
{"reqId":"9tDJIsap1yBi1n1Z3dhP","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contact\/810\/photo?refresh=0.09047408152284286"}
```

And these when opening a contact with an image:

```
{"reqId":"9tDJIsap1yBi1n1Z3dhP","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 4 passed to OCA\\Contacts\\Controller\\ContactPhotoController::__construct() must implement interface OCP\\ICache, instance of OC\\Cache\\File given, called in \/home\/jan\/owncloud\/apps\/contacts\/lib\/dispatcher.php on line 98 and defined at \/home\/jan\/owncloud\/apps\/contacts\/lib\/controller\/contactphotocontroller.php#31","level":0,"time":"2015-06-30T12:39:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contact\/810\/photo?refresh=0.09047408152284286"}
{"reqId":"9tDJIsap1yBi1n1Z3dhP","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Contacts\\Utils\\TemporaryPhoto::create() must implement interface OCP\\ICache, instance of OC\\Cache\\File given, called in \/home\/jan\/owncloud\/apps\/contacts\/lib\/controller\/contactphotocontroller.php on line 52 and defined at \/home\/jan\/owncloud\/apps\/contacts\/lib\/utils\/temporaryphoto.php#102","level":0,"time":"2015-06-30T12:39:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contact\/810\/photo?refresh=0.09047408152284286"}
{"reqId":"9tDJIsap1yBi1n1Z3dhP","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Contacts\\Utils\\TemporaryPhoto\\Contact::__construct() must implement interface OCP\\ICache, instance of OC\\Cache\\File given, called in \/home\/jan\/owncloud\/apps\/contacts\/lib\/utils\/temporaryphoto.php on line 104 and defined at \/home\/jan\/owncloud\/apps\/contacts\/lib\/utils\/temporaryphoto\/contact.php#41","level":0,"time":"2015-06-30T12:39:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contact\/810\/photo?refresh=0.09047408152284286"}
{"reqId":"9tDJIsap1yBi1n1Z3dhP","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\\Contacts\\Utils\\TemporaryPhoto::__construct() must implement interface OCP\\ICache, instance of OC\\Cache\\File given, called in \/home\/jan\/owncloud\/apps\/contacts\/lib\/utils\/temporaryphoto\/contact.php on line 49 and defined at \/home\/jan\/owncloud\/apps\/contacts\/lib\/utils\/temporaryphoto.php#90","level":0,"time":"2015-06-30T12:39:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contact\/810\/photo?refresh=0.09047408152284286"}
{"reqId":"9tDJIsap1yBi1n1Z3dhP","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-06-30T12:39:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contact\/810\/photo?refresh=0.09047408152284286"}
{"reqId":"9tDJIsap1yBi1n1Z3dhP","remoteAddr":"127.0.0.1","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-06-30T12:39:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contact\/810\/photo?refresh=0.09047408152284286"}
```

**Comment by DeepDiver1975** [comment]
> Nice! This fixes the photos in the Mail app and in the detail view of the contacts app. However, they are still not shown in the list view of the contacts app.

there is another PR to fix this #936

**Comment by DeepDiver1975** [comment]
> {"reqId":"9tDJIsap1yBi1n1Z3dhP","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 4 passed to OCA\Contacts\Controller\ContactPhotoController::__construct() must implement interface OCP\ICache, instance of OC\Cache\File given, called in \/home\/jan\/owncloud\/apps\/contacts\/lib\/dispatcher.php on line 98 and defined at \/home\/jan\/owncloud\/apps\/contacts\/lib\/controller\/contactphotocontroller.php#31","level":0,"time":"2015-06-30T12:39:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contact\/810\/photo?refresh=0.09047408152284286"} {"reqId":"9tDJIsap1yBi1n1Z3dhP","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\Contacts\Utils\TemporaryPhoto::create() must implement interface OCP\ICache, instance of OC\Cache\File given, called in \/home\/jan\/owncloud\/apps\/contacts\/lib\/controller\/contactphotocontroller.php on line 52 and defined at \/home\/jan\/owncloud\/apps\/contacts\/lib\/utils\/temporaryphoto.php#102","level":0,"time":"2015-06-30T12:39:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contact\/810\/photo?refresh=0.09047408152284286"} {"reqId":"9tDJIsap1yBi1n1Z3dhP","remoteAddr":"127.0.0.1","app":"PHP","message":"Argument 1 passed to OCA\Contacts\Utils\TemporaryPhoto\Contact::__construct() must implement interface OCP\ICache, instance of OC\Cache\File given, called in \/home\/jan\/owncloud\/apps\/contacts\/lib\/utils\/temporaryphoto.php on line 104 and defined at \/home\/jan\/owncloud\/apps\/contacts\/lib\/utils\/temporaryphoto\/contact.php#41","level":0,"time":"2015-06-30T12:39:56+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contact\/810\/photo?refresh=0.09047408152284286"}

fixed in core - please rebase

**Comment by DeepDiver1975** [comment]
> {"reqId":"8oD4\/6sr\/MVyXVBrNO\/s","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:47+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/"} {"reqId":"A9jmyJhOywEJ30KhOpXe","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:50+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/connectors\/%7Bbackend%7D"} {"reqId":"a2uTfHPSzzaFeZZQz7SW","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:50+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/groups\/"} {"reqId":"OOJc3CHou0yBRVfGyBxO","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:50+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbooks\/"} {"reqId":"diJhu1\/8di5KqHiDQGZK","remoteAddr":"127.0.0.1","app":"no app in context","message":"Accessing the API class is deprecated! Use the appropriate services instead!","level":0,"time":"2015-06-30T12:39:50+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/contacts\/addressbook\/local\/4\/contacts"}

fixed in #940

**Comment by jancborchardt** [comment]
Ok, if the issues I mentioned are separate I guess this is a :+1: from me. :) Huge thanks!

**Comment by LEDfan** [comment]
Wooohoo :smiley: I tested this branch and the branch of #936 (by merging the two) and it works perfectly! Great work ! :+1:

**Comment by j-ed** [comment]
I'm still finding `OC_Image->fixOrientation() Image is not a JPEG.` messages in the log file of ownCloud 8.2.1 and contacts v0.5.0.0 when the contacts app is opened. Is there a specific reason why the patches haven't been applied to the latest branch yet?

**Pull request merged**
