### PR TITLE
Adding l10n.pl for translation sync with transifex.

### PR DESCRIPTION
**Pull request by DeepDiver1975**
Jenkins job at https://ci.tmit.eu/job/translation-sync-contacts/

@tanghus

### CODE REVIEW

**Comment by tanghus** [comment]
Awesome, thx :)

**Comment by DeepDiver1975** [comment]
will sync every night from now on:
https://ci.tmit.eu/job/translation-sync-contacts/1/console

**Comment by tanghus** [comment]
Oops, it seems it doesn't like javascript comments. Should I worry about that?
BTW, is it possible to get general CI on commits? I admittedly sometimes forget running the tests manually, and I only run them for MySQL.

**Comment by DeepDiver1975** [comment]
regarding ci:
I need to setup the ci stuff for all apps, which left the apps repo. Will take some time - sorry.

regarding javascript:
Can you point me to an example? I'll dig into it then

**Comment by tanghus** [comment]
>  I need to setup the ci stuff for all apps, which left the apps repo. Will take some time - sorry.

No worries :)

wrt. the javascript in https://ci.tmit.eu/job/translation-sync-contacts/1/console it says for example:

`./js/app.js:268: warning: unterminated string` which is https://github.com/owncloud/contacts/blob/master/js/app.js#L268
It also happens for /*\* */ comments for example in `./js/addressbooks.js:350: warning: unterminated string` at https://github.com/owncloud/contacts/blob/master/js/addressbooks.js#L350

**Comment by DeepDiver1975** [comment]
We can ignore these warnings as we talk about comments which are not translated.

**Comment by tanghus** [comment]
k, thx

**Pull request merged**
